window.MUSIC_LIBRARY = Object.freeze([
  {
    "id": "library-001",
    "title": "直到你降临",
    "artist": "阿肆",
    "album": "直到你降临",
    "duration": 279.407,
    "sortOrder": 0,
    "audioUrl": "./assets/music/audio/001.mp3",
    "coverUrl": "./assets/music/covers/001.webp",
    "lyricsUrl": "./assets/music/lyrics/001.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-002",
    "title": "我愿",
    "artist": "阿虾",
    "album": "我愿",
    "duration": 221.0,
    "sortOrder": 1,
    "audioUrl": "./assets/music/audio/002.mp3",
    "coverUrl": "./assets/music/covers/002.webp",
    "lyricsUrl": "./assets/music/lyrics/002.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-003",
    "title": "尘土",
    "artist": "安朕宇",
    "album": "尘土（单曲版）",
    "duration": 235.541,
    "sortOrder": 2,
    "audioUrl": "./assets/music/audio/003.mp3",
    "coverUrl": "./assets/music/covers/003.webp",
    "lyricsUrl": "./assets/music/lyrics/003.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-004",
    "title": "好久不见(国)",
    "artist": "陈奕迅",
    "album": "The 1st Eleven Years 然后呢？",
    "duration": 250.543,
    "sortOrder": 3,
    "audioUrl": "./assets/music/audio/004.mp3",
    "coverUrl": "./assets/music/covers/004.webp",
    "lyricsUrl": "./assets/music/lyrics/004.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-005",
    "title": "谁家",
    "artist": "池鱼",
    "album": "谁家",
    "duration": 186.735,
    "sortOrder": 4,
    "audioUrl": "./assets/music/audio/005.mp3",
    "coverUrl": "./assets/music/covers/005.webp",
    "lyricsUrl": "./assets/music/lyrics/005.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-006",
    "title": "我与世界的帧帧瞬间",
    "artist": "崔十八 / 北夜 / 听潮阁",
    "album": "我与世界的帧帧瞬间",
    "duration": 189.499,
    "sortOrder": 5,
    "audioUrl": "./assets/music/audio/006.mp3",
    "coverUrl": "./assets/music/covers/006.webp",
    "lyricsUrl": "./assets/music/lyrics/006.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-007",
    "title": "我爱着远方的一个人",
    "artist": "大碗小面",
    "album": "我爱着远方的一个人（抖音热播）",
    "duration": 194.724,
    "sortOrder": 6,
    "audioUrl": "./assets/music/audio/007.mp3",
    "coverUrl": "./assets/music/covers/007.webp",
    "lyricsUrl": "./assets/music/lyrics/007.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-008",
    "title": "消散对白",
    "artist": "杜宣达",
    "album": "消散对白",
    "duration": 214.57,
    "sortOrder": 7,
    "audioUrl": "./assets/music/audio/008.mp3",
    "coverUrl": "./assets/music/covers/008.webp",
    "lyricsUrl": "./assets/music/lyrics/008.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-009",
    "title": "指纹",
    "artist": "杜宣达",
    "album": "指纹",
    "duration": 240.272,
    "sortOrder": 8,
    "audioUrl": "./assets/music/audio/009.mp3",
    "coverUrl": "./assets/music/covers/009.webp",
    "lyricsUrl": "./assets/music/lyrics/009.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-010",
    "title": "陷入爱情 (镜头对准你眼睛)",
    "artist": "二硕 / 2OS",
    "album": "陷入爱情 (镜头对准你眼睛)",
    "duration": 159.577,
    "sortOrder": 9,
    "audioUrl": "./assets/music/audio/010.mp3",
    "coverUrl": "./assets/music/covers/010.webp",
    "lyricsUrl": "./assets/music/lyrics/010.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-011",
    "title": "和宇宙的温柔关联",
    "artist": "房东的猫",
    "album": "玫瑰凭证",
    "duration": 267.012,
    "sortOrder": 10,
    "audioUrl": "./assets/music/audio/011.mp3",
    "coverUrl": "./assets/music/covers/011.webp",
    "lyricsUrl": "./assets/music/lyrics/011.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-012",
    "title": "我搞不懂",
    "artist": "甘草片r",
    "album": "我搞不懂",
    "duration": 208.728,
    "sortOrder": 11,
    "audioUrl": "./assets/music/audio/012.mp3",
    "coverUrl": "./assets/music/covers/012.webp",
    "lyricsUrl": "./assets/music/lyrics/012.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-013",
    "title": "知我",
    "artist": "国风堂 / 哦漏",
    "album": "知我",
    "duration": 277.321,
    "sortOrder": 12,
    "audioUrl": "./assets/music/audio/013.mp3",
    "coverUrl": "./assets/music/covers/013.webp",
    "lyricsUrl": "./assets/music/lyrics/013.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-014",
    "title": "你的",
    "artist": "贺仙人",
    "album": "你的",
    "duration": 189.706,
    "sortOrder": 13,
    "audioUrl": "./assets/music/audio/014.mp3",
    "coverUrl": "./assets/music/covers/014.webp",
    "lyricsUrl": "./assets/music/lyrics/014.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-015",
    "title": "是想你的声音啊",
    "artist": "江偌绮（傲七爷）",
    "album": "是想你的声音啊",
    "duration": 234.812,
    "sortOrder": 14,
    "audioUrl": "./assets/music/audio/015.mp3",
    "coverUrl": "./assets/music/covers/015.webp",
    "lyricsUrl": "./assets/music/lyrics/015.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-016",
    "title": "不懂什么大道理",
    "artist": "九重临",
    "album": "不懂什么大道理",
    "duration": 237.0,
    "sortOrder": 15,
    "audioUrl": "./assets/music/audio/016.mp3",
    "coverUrl": "./assets/music/covers/016.webp",
    "lyricsUrl": "./assets/music/lyrics/016.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-017",
    "title": "归去来",
    "artist": "九重临",
    "album": "空山语",
    "duration": 214.386,
    "sortOrder": 16,
    "audioUrl": "./assets/music/audio/017.mp3",
    "coverUrl": "./assets/music/covers/017.webp",
    "lyricsUrl": "./assets/music/lyrics/017.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-018",
    "title": "君知我",
    "artist": "九重临",
    "album": "君知我",
    "duration": 259.286,
    "sortOrder": 17,
    "audioUrl": "./assets/music/audio/018.mp3",
    "coverUrl": "./assets/music/covers/018.webp",
    "lyricsUrl": "./assets/music/lyrics/018.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-019",
    "title": "乐园",
    "artist": "九重临",
    "album": "乐园",
    "duration": 140.769,
    "sortOrder": 18,
    "audioUrl": "./assets/music/audio/019.mp3",
    "coverUrl": "./assets/music/covers/019.webp",
    "lyricsUrl": "./assets/music/lyrics/019.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-020",
    "title": "眠雨书",
    "artist": "九重临",
    "album": "眠雨书",
    "duration": 237.0,
    "sortOrder": 19,
    "audioUrl": "./assets/music/audio/020.mp3",
    "coverUrl": "./assets/music/covers/020.webp",
    "lyricsUrl": "./assets/music/lyrics/020.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-021",
    "title": "平安岁",
    "artist": "九重临",
    "album": "眠雨书",
    "duration": 240.0,
    "sortOrder": 20,
    "audioUrl": "./assets/music/audio/021.mp3",
    "coverUrl": "./assets/music/covers/021.webp",
    "lyricsUrl": "./assets/music/lyrics/021.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-022",
    "title": "若沉浊不可与语",
    "artist": "九重临",
    "album": "无端涯",
    "duration": 224.242,
    "sortOrder": 21,
    "audioUrl": "./assets/music/audio/022.mp3",
    "coverUrl": "./assets/music/covers/022.webp",
    "lyricsUrl": "./assets/music/lyrics/022.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-023",
    "title": "三季虫",
    "artist": "九重临",
    "album": "三季虫",
    "duration": 289.735,
    "sortOrder": 22,
    "audioUrl": "./assets/music/audio/023.mp3",
    "coverUrl": "./assets/music/covers/023.webp",
    "lyricsUrl": "./assets/music/lyrics/023.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-024",
    "title": "叹云兮",
    "artist": "鞠婧祎",
    "album": "叹云兮",
    "duration": 283.059,
    "sortOrder": 23,
    "audioUrl": "./assets/music/audio/024.mp3",
    "coverUrl": "./assets/music/covers/024.webp",
    "lyricsUrl": "./assets/music/lyrics/024.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-025",
    "title": "总有一天你会出现在我身边",
    "artist": "棱镜乐队",
    "album": "一次有预谋的初次相遇",
    "duration": 270.0,
    "sortOrder": 24,
    "audioUrl": "./assets/music/audio/025.mp3",
    "coverUrl": "./assets/music/covers/025.webp",
    "lyricsUrl": "./assets/music/lyrics/025.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-026",
    "title": "甲乙丙丁 (你我怎么两清)",
    "artist": "李佳薇",
    "album": "甲乙丙丁",
    "duration": 210.462,
    "sortOrder": 25,
    "audioUrl": "./assets/music/audio/026.mp3",
    "coverUrl": "./assets/music/covers/026.webp",
    "lyricsUrl": "./assets/music/lyrics/026.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-027",
    "title": "一往情深的恋人",
    "artist": "李健",
    "album": "音乐傲骨",
    "duration": 285.587,
    "sortOrder": 26,
    "audioUrl": "./assets/music/audio/027.mp3",
    "coverUrl": "./assets/music/covers/027.webp",
    "lyricsUrl": "./assets/music/lyrics/027.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-028",
    "title": "情歌",
    "artist": "梁静茹",
    "album": "现在开始我爱你",
    "duration": 263.293,
    "sortOrder": 27,
    "audioUrl": "./assets/music/audio/028.mp3",
    "coverUrl": "./assets/music/covers/028.webp",
    "lyricsUrl": "./assets/music/lyrics/028.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-029",
    "title": "同手同脚",
    "artist": "林宜融",
    "album": "星光2班 你们是我的星光",
    "duration": 251.52,
    "sortOrder": 28,
    "audioUrl": "./assets/music/audio/029.mp3",
    "coverUrl": "./assets/music/covers/029.webp",
    "lyricsUrl": "./assets/music/lyrics/029.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-030",
    "title": "黄昏海岸线",
    "artist": "林怡婕",
    "album": "黄昏海岸线",
    "duration": 180.915,
    "sortOrder": 29,
    "audioUrl": "./assets/music/audio/030.mp3",
    "coverUrl": "./assets/music/covers/030.webp",
    "lyricsUrl": "./assets/music/lyrics/030.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-031",
    "title": "小树",
    "artist": "林逾",
    "album": "免责条款",
    "duration": 237.984,
    "sortOrder": 30,
    "audioUrl": "./assets/music/audio/031.mp3",
    "coverUrl": "./assets/music/covers/031.webp",
    "lyricsUrl": "./assets/music/lyrics/031.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-032",
    "title": "深海",
    "artist": "刘森",
    "album": "华北浪革",
    "duration": 294.227,
    "sortOrder": 31,
    "audioUrl": "./assets/music/audio/032.mp3",
    "coverUrl": "./assets/music/covers/032.webp",
    "lyricsUrl": "./assets/music/lyrics/032.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-033",
    "title": "刻在我心底的名字",
    "artist": "卢广仲",
    "album": "刻在我心底的名字",
    "duration": 320.166,
    "sortOrder": 32,
    "audioUrl": "./assets/music/audio/033.mp3",
    "coverUrl": "./assets/music/covers/033.webp",
    "lyricsUrl": "./assets/music/lyrics/033.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-034",
    "title": "季节性想念",
    "artist": "陆杰awr",
    "album": "季节性想念",
    "duration": 208.0,
    "sortOrder": 33,
    "audioUrl": "./assets/music/audio/034.mp3",
    "coverUrl": "./assets/music/covers/034.webp",
    "lyricsUrl": "./assets/music/lyrics/034.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-035",
    "title": "路不通就转弯",
    "artist": "陆杰awr",
    "album": "路不通就转弯",
    "duration": 194.936,
    "sortOrder": 34,
    "audioUrl": "./assets/music/audio/035.mp3",
    "coverUrl": "./assets/music/covers/035.webp",
    "lyricsUrl": "./assets/music/lyrics/035.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-036",
    "title": "呓语",
    "artist": "毛不易",
    "album": "小王",
    "duration": 271.193,
    "sortOrder": 35,
    "audioUrl": "./assets/music/audio/036.mp3",
    "coverUrl": "./assets/music/covers/036.webp",
    "lyricsUrl": "./assets/music/lyrics/036.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-037",
    "title": "长大",
    "artist": "容祖儿",
    "album": "答案之书",
    "duration": 218.935,
    "sortOrder": 36,
    "audioUrl": "./assets/music/audio/037.mp3",
    "coverUrl": "./assets/music/covers/037.webp",
    "lyricsUrl": "./assets/music/lyrics/037.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-038",
    "title": "世界上有两个我",
    "artist": "孙天宇",
    "album": "世界上有两个我",
    "duration": 214.5,
    "sortOrder": 37,
    "audioUrl": "./assets/music/audio/038.mp3",
    "coverUrl": "./assets/music/covers/038.webp",
    "lyricsUrl": "./assets/music/lyrics/038.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-039",
    "title": "开始懂了",
    "artist": "孙燕姿",
    "album": "我要的幸福",
    "duration": 271.493,
    "sortOrder": 38,
    "audioUrl": "./assets/music/audio/039.mp3",
    "coverUrl": "./assets/music/covers/039.webp",
    "lyricsUrl": "./assets/music/lyrics/039.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-040",
    "title": "冬与你",
    "artist": "万乐体 / 鱼骨妹",
    "album": "冬与你",
    "duration": 112.864,
    "sortOrder": 39,
    "audioUrl": "./assets/music/audio/040.mp3",
    "coverUrl": "./assets/music/covers/040.webp",
    "lyricsUrl": "./assets/music/lyrics/040.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-041",
    "title": "晴 (live)",
    "artist": "汪苏泷",
    "album": "声生不息·华流季 第5期",
    "duration": 259.448,
    "sortOrder": 40,
    "audioUrl": "./assets/music/audio/041.mp3",
    "coverUrl": "./assets/music/covers/041.webp",
    "lyricsUrl": "./assets/music/lyrics/041.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-042",
    "title": "像鱼",
    "artist": "王贰浪",
    "album": "像鱼",
    "duration": 285.272,
    "sortOrder": 41,
    "audioUrl": "./assets/music/audio/042.mp3",
    "coverUrl": "./assets/music/covers/042.webp",
    "lyricsUrl": "./assets/music/lyrics/042.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-043",
    "title": "Again",
    "artist": "王极",
    "album": "Again",
    "duration": 122.207,
    "sortOrder": 42,
    "audioUrl": "./assets/music/audio/043.mp3",
    "coverUrl": "./assets/music/covers/043.webp",
    "lyricsUrl": "./assets/music/lyrics/043.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-044",
    "title": "大城小爱",
    "artist": "王力宏",
    "album": "2006 MP3人气超强总冠军",
    "duration": 224.98,
    "sortOrder": 43,
    "audioUrl": "./assets/music/audio/044.mp3",
    "coverUrl": "./assets/music/covers/044.webp",
    "lyricsUrl": "./assets/music/lyrics/044.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-045",
    "title": "心许百年",
    "artist": "王天戈",
    "album": "心许百年",
    "duration": 211.14,
    "sortOrder": 44,
    "audioUrl": "./assets/music/audio/045.mp3",
    "coverUrl": "./assets/music/covers/045.webp",
    "lyricsUrl": "./assets/music/lyrics/045.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-046",
    "title": "女孩",
    "artist": "韦礼安",
    "album": "硬戳",
    "duration": 306.293,
    "sortOrder": 45,
    "audioUrl": "./assets/music/audio/046.mp3",
    "coverUrl": "./assets/music/covers/046.webp",
    "lyricsUrl": "./assets/music/lyrics/046.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-047",
    "title": "失眠了",
    "artist": "吴琳珂Moske",
    "album": "失眠了",
    "duration": 254.208,
    "sortOrder": 46,
    "audioUrl": "./assets/music/audio/047.mp3",
    "coverUrl": "./assets/music/covers/047.webp",
    "lyricsUrl": "./assets/music/lyrics/047.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-048",
    "title": "去见你",
    "artist": "徐秉龙",
    "album": "去见你",
    "duration": 170.529,
    "sortOrder": 47,
    "audioUrl": "./assets/music/audio/048.mp3",
    "coverUrl": "./assets/music/covers/048.webp",
    "lyricsUrl": "./assets/music/lyrics/048.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-049",
    "title": "心事",
    "artist": "徐秉龙",
    "album": "零零",
    "duration": 224.0,
    "sortOrder": 48,
    "audioUrl": "./assets/music/audio/049.mp3",
    "coverUrl": "./assets/music/covers/049.webp",
    "lyricsUrl": "./assets/music/lyrics/049.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-050",
    "title": "蘇州河 (慕容雪 - Mandarin Version)",
    "artist": "薛凯琪",
    "album": "Read Me",
    "duration": 240.52,
    "sortOrder": 49,
    "audioUrl": "./assets/music/audio/050.mp3",
    "coverUrl": "./assets/music/covers/050.webp",
    "lyricsUrl": "./assets/music/lyrics/050.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-051",
    "title": "动物世界",
    "artist": "薛之谦",
    "album": "渡",
    "duration": 230.457,
    "sortOrder": 50,
    "audioUrl": "./assets/music/audio/051.mp3",
    "coverUrl": "./assets/music/covers/051.webp",
    "lyricsUrl": "./assets/music/lyrics/051.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-052",
    "title": "顽疾 (Live)",
    "artist": "薛之谦",
    "album": "音乐缘计划2 第1期",
    "duration": 290.398,
    "sortOrder": 51,
    "audioUrl": "./assets/music/audio/052.mp3",
    "coverUrl": "./assets/music/covers/052.webp",
    "lyricsUrl": "./assets/music/lyrics/052.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-053",
    "title": "小尖尖",
    "artist": "薛之谦 / 韩红",
    "album": "天外来物",
    "duration": 235.49,
    "sortOrder": 52,
    "audioUrl": "./assets/music/audio/053.mp3",
    "coverUrl": "./assets/music/covers/053.webp",
    "lyricsUrl": "./assets/music/lyrics/053.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-054",
    "title": "时间煮雨 (Live)",
    "artist": "薛之谦 / 林乐仪",
    "album": "中国新声代第四季 第9期",
    "duration": 126.0,
    "sortOrder": 53,
    "audioUrl": "./assets/music/audio/054.mp3",
    "coverUrl": "./assets/music/covers/054.webp",
    "lyricsUrl": "./assets/music/lyrics/054.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-055",
    "title": "歌曲：假如（live）",
    "artist": "闫妮/殷桃/宋佳/蒋欣",
    "album": "2025年中央广播电视总台春节联欢晚会",
    "duration": 219.669,
    "sortOrder": 54,
    "audioUrl": "./assets/music/audio/055.mp3",
    "coverUrl": "./assets/music/covers/055.webp",
    "lyricsUrl": "./assets/music/lyrics/055.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-056",
    "title": "关于你",
    "artist": "姚晓棠",
    "album": "关于你",
    "duration": 255.839,
    "sortOrder": 55,
    "audioUrl": "./assets/music/audio/056.mp3",
    "coverUrl": "./assets/music/covers/056.webp",
    "lyricsUrl": "./assets/music/lyrics/056.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-057",
    "title": "抑人",
    "artist": "银河快递 / 门尼",
    "album": "抑人",
    "duration": 219.929,
    "sortOrder": 56,
    "audioUrl": "./assets/music/audio/057.mp3",
    "coverUrl": "./assets/music/covers/057.webp",
    "lyricsUrl": "./assets/music/lyrics/057.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-058",
    "title": "体面 (Live)",
    "artist": "于文文",
    "album": "时光音乐会老友记 第1期",
    "duration": 259.593,
    "sortOrder": 57,
    "audioUrl": "./assets/music/audio/058.mp3",
    "coverUrl": "./assets/music/covers/058.webp",
    "lyricsUrl": "./assets/music/lyrics/058.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-059",
    "title": "白梨花 (Live)",
    "artist": "袁娅维TIA RAY / 王睿卓",
    "album": "音你而来第二季 第7期",
    "duration": 259.355,
    "sortOrder": 58,
    "audioUrl": "./assets/music/audio/059.mp3",
    "coverUrl": "./assets/music/covers/059.webp",
    "lyricsUrl": "./assets/music/lyrics/059.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-060",
    "title": "云中的Angel",
    "artist": "张杰",
    "album": "听！我们的歌",
    "duration": 242.602,
    "sortOrder": 59,
    "audioUrl": "./assets/music/audio/060.mp3",
    "coverUrl": "./assets/music/covers/060.webp",
    "lyricsUrl": "./assets/music/lyrics/060.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-061",
    "title": "看着我的眼睛说 (Live版)",
    "artist": "张远 / 姚晓棠",
    "album": "天赐的声音第六季 第7期",
    "duration": 280.288,
    "sortOrder": 60,
    "audioUrl": "./assets/music/audio/061.mp3",
    "coverUrl": "./assets/music/covers/061.webp",
    "lyricsUrl": "./assets/music/lyrics/061.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-062",
    "title": "可不可以",
    "artist": "张紫豪",
    "album": "可不可以",
    "duration": 240.889,
    "sortOrder": 61,
    "audioUrl": "./assets/music/audio/062.mp3",
    "coverUrl": "./assets/music/covers/062.webp",
    "lyricsUrl": "./assets/music/lyrics/062.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-063",
    "title": "思念成风飘向你",
    "artist": "张紫宁",
    "album": "思念成风飘向你",
    "duration": 283.497,
    "sortOrder": 62,
    "audioUrl": "./assets/music/audio/063.mp3",
    "coverUrl": "./assets/music/covers/063.webp",
    "lyricsUrl": "./assets/music/lyrics/063.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-064",
    "title": "伶人",
    "artist": "赵钶 / 张弛",
    "album": "伶人",
    "duration": 277.399,
    "sortOrder": 63,
    "audioUrl": "./assets/music/audio/064.mp3",
    "coverUrl": "./assets/music/covers/064.webp",
    "lyricsUrl": "./assets/music/lyrics/064.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-065",
    "title": "有幸",
    "artist": "赵砚卿",
    "album": "有幸",
    "duration": 222.0,
    "sortOrder": 64,
    "audioUrl": "./assets/music/audio/065.mp3",
    "coverUrl": "./assets/music/covers/065.webp",
    "lyricsUrl": "./assets/music/lyrics/065.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-066",
    "title": "雨天",
    "artist": "郑润泽",
    "album": "雨天（你能体谅我有雨天）",
    "duration": 180.0,
    "sortOrder": 65,
    "audioUrl": "./assets/music/audio/066.mp3",
    "coverUrl": "./assets/music/covers/066.webp",
    "lyricsUrl": "./assets/music/lyrics/066.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-067",
    "title": "就这样爱着你",
    "artist": "粥粥和小伙 / 粥粥",
    "album": "就这样爱着你",
    "duration": 228.181,
    "sortOrder": 66,
    "audioUrl": "./assets/music/audio/067.mp3",
    "coverUrl": "./assets/music/covers/067.webp",
    "lyricsUrl": "./assets/music/lyrics/067.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-068",
    "title": "与山记",
    "artist": "祝青 / 万象凡音",
    "album": "拾遗 (国风天华)",
    "duration": 224.5,
    "sortOrder": 67,
    "audioUrl": "./assets/music/audio/068.mp3",
    "coverUrl": "./assets/music/covers/068.webp",
    "lyricsUrl": "./assets/music/lyrics/068.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-069",
    "title": "算了吧",
    "artist": "Aioz / 张天枢 / 刘思达",
    "album": "算了吧",
    "duration": 186.0,
    "sortOrder": 68,
    "audioUrl": "./assets/music/audio/069.mp3",
    "coverUrl": "./assets/music/covers/069.webp",
    "lyricsUrl": "./assets/music/lyrics/069.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-070",
    "title": "星降る海",
    "artist": "Aqu3ra / 早見沙織",
    "album": "超かぐや姫！",
    "duration": 253.441,
    "sortOrder": 69,
    "audioUrl": "./assets/music/audio/070.mp3",
    "coverUrl": "./assets/music/covers/070.webp",
    "lyricsUrl": "./assets/music/lyrics/070.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-071",
    "title": "So Beautiful",
    "artist": "DPR IAN",
    "album": "So Beautiful",
    "duration": 187.227,
    "sortOrder": 70,
    "audioUrl": "./assets/music/audio/071.mp3",
    "coverUrl": "./assets/music/covers/071.webp",
    "lyricsUrl": "./assets/music/lyrics/071.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-072",
    "title": "再见（good bye）",
    "artist": "G.E.M.邓紫棋",
    "album": "新的心跳",
    "duration": 206.053,
    "sortOrder": 71,
    "audioUrl": "./assets/music/audio/072.mp3",
    "coverUrl": "./assets/music/covers/072.webp",
    "lyricsUrl": "./assets/music/lyrics/072.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-073",
    "title": "我该怎么开口",
    "artist": "Huela静静静 / 家文",
    "album": "我该怎么开口",
    "duration": 174.474,
    "sortOrder": 72,
    "audioUrl": "./assets/music/audio/073.mp3",
    "coverUrl": "./assets/music/covers/073.webp",
    "lyricsUrl": "./assets/music/lyrics/073.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-074",
    "title": "太要命",
    "artist": "KUAN / 阿达娃",
    "album": "太要命",
    "duration": 191.25,
    "sortOrder": 73,
    "audioUrl": "./assets/music/audio/074.mp3",
    "coverUrl": "./assets/music/covers/074.webp",
    "lyricsUrl": "./assets/music/lyrics/074.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-075",
    "title": "追光者 - 纯人声.ver（Cover 岑宁儿）",
    "artist": "Pauu",
    "album": "今天你西柚了吗",
    "duration": 235.288,
    "sortOrder": 74,
    "audioUrl": "./assets/music/audio/075.mp3",
    "coverUrl": "./assets/music/covers/075.webp",
    "lyricsUrl": "./assets/music/lyrics/075.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-076",
    "title": "ワールドイズマイン (かぐや&月見ヤチヨ ver.) [CPK! Remix]",
    "artist": "ryo (supercell) / 夏吉ゆうこ / 早見沙織",
    "album": "Ex-Otogibanashi",
    "duration": 226.0,
    "sortOrder": 75,
    "audioUrl": "./assets/music/audio/076.mp3",
    "coverUrl": "./assets/music/covers/076.webp",
    "lyricsUrl": "./assets/music/lyrics/076.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-077",
    "title": "陪我走过春夏秋冬",
    "artist": "Sing",
    "album": "从天而来的爱和恩典(来自网络)",
    "duration": 338.977,
    "sortOrder": 76,
    "audioUrl": "./assets/music/audio/077.mp3",
    "coverUrl": "./assets/music/covers/077.webp",
    "lyricsUrl": "./assets/music/lyrics/077.lrc",
    "timedLyrics": false
  },
  {
    "id": "library-078",
    "title": "lovE不发音",
    "artist": "soldier / 鬼才",
    "album": "lovE不发音",
    "duration": 135.68,
    "sortOrder": 77,
    "audioUrl": "./assets/music/audio/078.mp3",
    "coverUrl": "./assets/music/covers/078.webp",
    "lyricsUrl": "./assets/music/lyrics/078.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-079",
    "title": "未完结的爱",
    "artist": "Zkaaai",
    "album": "未完结的爱",
    "duration": 221.75,
    "sortOrder": 78,
    "audioUrl": "./assets/music/audio/079.mp3",
    "coverUrl": "./assets/music/covers/079.webp",
    "lyricsUrl": "./assets/music/lyrics/079.lrc",
    "timedLyrics": true
  },
  {
    "id": "library-080",
    "title": "病态的爱",
    "artist": "Zkaaai / 哈利白特",
    "album": "1:20",
    "duration": 201.176,
    "sortOrder": 79,
    "audioUrl": "./assets/music/audio/080.mp3",
    "coverUrl": "./assets/music/covers/080.webp",
    "lyricsUrl": "./assets/music/lyrics/080.lrc",
    "timedLyrics": true
  }
]);
